import type { Metadata } from 'next'
import './globals.css'
import { Toaster } from 'sonner'
import Providers from '@/app/(providers)/query-providers'
import { ThemeProvider } from 'next-themes'
import '@smastrom/react-rating/style.css'
import { inter, montserrat, poppins } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Telescope',
  description: 'Generated by create Pronutrir LTDA',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat} ${inter} ${poppins} overflow-x-hidden bg-[hsl(230,75,98)] dark:bg-slate-950`}
      >
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
